# Generated by Django 4.2.4 on 2023-09-21 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoveEase', '0004_rename_country_user_registration_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_registration',
            name='MoveEasePerson',
            field=models.BooleanField(choices=[(True, True), (False, False)], default=False),
        ),
    ]
