# Generated by Django 4.2.4 on 2023-09-21 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoveEase', '0005_alter_user_registration_moveeaseperson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_registration',
            name='delivery_person',
            field=models.BooleanField(choices=[(True, True), (False, False)], default=False),
        ),
    ]
