# Generated by Django 4.2.4 on 2023-09-28 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MoveEase', '0009_alter_user_registration_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bhk_type', models.CharField(max_length=10)),
                ('service_time', models.DateTimeField()),
                ('selected_vehicle', models.CharField(max_length=50)),
                ('shifting_from', models.CharField(max_length=100)),
                ('shifting_to', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoveEase.user_registration')),
            ],
        ),
    ]
