# Generated by Django 4.2.4 on 2023-09-28 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MoveEase', '0010_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shifting_from', models.CharField(max_length=100)),
                ('shifting_to', models.CharField(max_length=100)),
                ('bhk_type', models.CharField(max_length=10)),
                ('service_time', models.DateTimeField()),
                ('selected_vehicle', models.CharField(max_length=50)),
                ('payment_status', models.BooleanField(default=False)),
                ('bill_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoveEase.user_registration')),
            ],
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
