# Generated by Django 4.2.4 on 2023-09-30 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoveEase', '0012_booking_detail_delete_booking_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_detail',
            name='deliver_status',
            field=models.BooleanField(default=False),
        ),
    ]
