# Generated by Django 4.2.4 on 2023-09-30 18:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MoveEase', '0013_booking_detail_deliver_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_detail',
            name='service_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
