# Generated by Django 4.2.4 on 2023-10-01 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoveEase', '0014_alter_booking_detail_service_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_detail',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
