# Generated by Django 4.2.4 on 2023-10-01 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoveEase', '0015_booking_detail_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_detail',
            name='service_time',
            field=models.DateTimeField(),
        ),
    ]
