# Generated by Django 4.2.4 on 2023-10-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoveEase', '0017_booking_detail_delivery_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_detail',
            name='delivery_person',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
