# Generated by Django 4.2.4 on 2023-10-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoveEase', '0018_alter_booking_detail_delivery_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(max_length=200)),
            ],
        ),
    ]
