# Generated by Django 4.2.4 on 2023-10-15 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoveEase', '0020_customers_review_delete_customer_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_registration',
            name='state',
            field=models.CharField(choices=[('Tamil Nadu', 'Tamil Nadu'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra')], max_length=100),
        ),
    ]
