# Generated by Django 4.2.4 on 2023-10-15 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MoveEase', '0021_alter_user_registration_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_registration',
            name='state',
        ),
    ]
